### PR TITLE
changed DeleteFolderItems to soft-delete and fix of null warnings

### LINKED ISSUE #72: Recursive Folder Deletion -> Soft Delete Content
Please change Folder recursive deletion to set the FolderUuid of every Credential that it contains to `null` and set DeletedTimeStamp to current.

That way the Credentials would be soft deleted and the User could restore them, if they accidentally did recursive.

### PR DESCRIPTION
**Pull request by MLB-on**
- Fix null warnings. #61 
- soft deletion of Credentials when Folder is deleted recursevly. closes #72

### CODE REVIEW

File: ApiEndpoints/Folders/Delete.cs [hunk 1]
```diff
@@ -81,6 +81,9 @@ private static void ClearFolder(Folder folder, DatabaseHandle databaseHandle)
     /// <param name="databaseHandle">Database to handle</param>
     private static void DeleteFolderItems(Folder folder, DatabaseHandle databaseHandle)
     {
-        databaseHandle.Credentials.RemoveRange(databaseHandle.Credentials.Where(c => c.FolderUuid == folder.Uuid));
+        foreach (Credential item in databaseHandle.Credentials.Where(c => c.FolderUuid == folder.Uuid))
+        {
+            item.DeletedTimestamp = (long)DateTime.UtcNow.Subtract(DateTime.UnixEpoch).TotalSeconds;
```
Comment (Jannik-Hm) [inline ApiEndpoints/Folders/Delete.cs:86]: Hey, just my understanding: does this only set the DeletedTimeStamp to the current time?

We need to set the folderUuid to `null` as well. Otherwise the credential will have a non-existing folder, once restored.

**Review by LightJack05 — CHANGES_REQUESTED** [review]
See comment by @Jannik-Hm

File: ApiEndpoints/Folders/Update.cs
Comment (LightJack05) [inline ApiEndpoints/Folders/Update.cs:1]: Would be better if you fix null warnings in a separate PR, keep one PR to one fix/feature. Fine for now though. ;)

File: ApiEndpoints/Folders/Delete.cs (hunk 1 above)
Comment (MLB-on) [reply ApiEndpoints/Folders/Delete.cs:86]: You are right.
I have added the missing line.

**Review by LightJack05 — APPROVED** [review]
